version: 1.1.{build}

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2015

configuration:
  - Release

platform: 
  - Win32
  
VisualStudioVersion: 14.0

build:
  project: vstudio\cjet binary and tests.sln