version: 1.1.0

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2015

configuration:
  - Release

platform: 
  - Win32
  
build_script:
- cmd: msbuild vstudio\cjet binary and tests.sln /p:VisualStudioVersion=14.0 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

 