version: 1.1.0

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2015

configuration:
  - Release

platform: 
  - Win32
  
environment:
  VisualStudioVersion: 14.0.25420.1

build:
  project: vstudio\cjet binary and tests.sln